/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ValidateBooking': EventHandler<{ bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string }, { topic: 'process-payment'; data: { bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string; amount: number } } | { topic: 'booking-failed'; data: { bookingId: string; eventId: string; seatId?: string | unknown; reason: string } }>
    'ProcessRefund': EventHandler<{ bookingId: string; eventId: string; customerEmail: string; amount: number }, never>
    'ProcessPayment': EventHandler<{ bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string; amount: number }, { topic: 'booking-confirmed'; data: { bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string; paymentId: string; amount: number } } | { topic: 'booking-failed'; data: { bookingId: string; eventId: string; seatId?: string | unknown; reason: string } }>
    'ProcessCancellation': EventHandler<{ bookingId: string; eventId: string; seatId: string | unknown; customerEmail: string; hadPayment: boolean; amount?: number }, { topic: 'refund-initiated'; data: { bookingId: string; eventId: string; customerEmail: string; amount: number } }>
    'ListEvents': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { events: Array<{ id: string; title: string; slug: string; price: number; description: string; thumbnail: string; totalSeats: number; availableSeats: number; createdAt: string }>; total: number }>, never>
    'ListCustomers': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { customers: Array<{ email: string; name: string; totalBookings: number; confirmedBookings: number; totalSpent: number; lastBookingAt?: string }>; total: number }>, never>
    'ListCustomerBookings': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { bookings: Array<{ id: string; eventId: string; eventTitle?: string; seatId?: string | unknown; status: string; amount?: number; createdAt: string }>; total: number }> | ApiResponse<400, { error: string }>, never>
    'GetEvent': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; title: string; slug: string; price: number; description: string; thumbnail: string; totalSeats: number; availableSeats: number; seatMap: Array<{ id: string; row: string; number: number; category: string; status: 'available' | 'held' | 'booked' }>; createdAt: string }> | ApiResponse<404, { error: string }>, never>
    'CreateEvent': ApiRouteHandler<{ title: string; slug: string; price: number; description?: string; thumbnail?: string; totalSeats: number; seatMap?: Array<{ id: string; row: string; number: number; category: 'vip' | 'regular'; price?: number }> }, ApiResponse<201, { id: string; title: string; slug: string; price: number; totalSeats: number; availableSeats: number; createdAt: string }> | ApiResponse<400, { error: string }>, never>
    'ListAllBookings': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { bookings: Array<{ id: string; eventId: string; eventTitle?: string; seatId?: string | unknown; customerName: string; customerEmail: string; status: string; amount?: number; paymentId?: string; createdAt: string; confirmedAt?: string; cancelledAt?: string; refundedAt?: string }>; total: number }>, never>
    'InitBooking': ApiRouteHandler<{ eventId: string; seatId?: string; customerName: string; customerEmail: string }, ApiResponse<201, { bookingId: string; eventId: string; seatId?: string; status: string; holdExpiresAt: string; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<409, { error: string }>, { topic: 'validate-booking'; data: { bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string } }>
    'HandleBookingFailed': EventHandler<{ bookingId: string; eventId: string; seatId?: string | unknown; reason: string }, never>
    'GetBooking': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; eventId: string; eventTitle?: string; seatId?: string | unknown; customerName: string; customerEmail: string; status: 'pending' | 'validating' | 'processing' | 'confirmed' | 'failed' | 'cancelled'; amount?: number; paymentId?: string; holdExpiresAt?: string; confirmedAt?: string; createdAt: string }> | ApiResponse<404, { error: string }>, never>
    'ConfirmBooking': EventHandler<{ bookingId: string; eventId: string; seatId: string | unknown; customerName: string; customerEmail: string; paymentId: string; amount: number }, never>
    'CancelBooking': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { bookingId: string; status: string; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'process-cancellation'; data: { bookingId: string; eventId: string; seatId: string | unknown; customerEmail: string; hadPayment: boolean; amount?: number } }>
  }
    
}